# Generated by Django 5.1.3 on 2024-11-13 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ename', models.CharField(max_length=50)),
                ('eaddr', models.CharField(max_length=50)),
                ('enum', models.IntegerField()),
                ('esal', models.FloatField()),
            ],
        ),
    ]
